# Generic:
#   optimizer: "worklist_scheduler"
#   num_questions: 1
#   mode: "dsub_local_worker"
#   workers:
#     generic_worker: 1

Calculator:
  optimizer: "worklist_scheduler"
  num_questions: 1
  mode: "dsub_cloud_worker
  workers:
    calculator_worker: 1

# Addition:
#   optimizer: "worklist_scheduler"
#   num_questions: 1
#   mode: "dsub_local_worker"
#   workers:
#     addition_worker: 1

# Subtraction:
#   optimizer: "worklist_scheduler"
#   num_questions: 1
#   mode: "dsub_local_worker"
#   workers:
#     subtraction_worker: 1

# Multiplication:
#   optimizer: "worklist_scheduler"
#   num_questions: 1
#   mode: "dsub_local_worker"
#   workers:
#     multiplication_worker: 1

# Division:
#   optimizer: "worklist_scheduler"
#   num_questions: 1
#   mode: "dsub_local_worker"
#   workers:
#     division_worker: 1
