# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sight/proto/widgets/pipeline/flume/flume.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.sight/proto/widgets/pipeline/flume/flume.proto\x12\x1bsight.x.widgets.flume.proto\" \n\x0f\x46lumeDoFnCreate\x12\r\n\x05label\x18\x01 \x01(\t\"\"\n\x11\x46lumeDoFnComplete\x12\r\n\x05label\x18\x01 \x01(\t\"Y\n\x10\x46lumeDoFnStartDo\x12\x16\n\x0einput_stage_id\x18\x01 \x01(\x03\x12\x15\n\rinput_item_id\x18\x02 \x01(\x03\x12\x16\n\x0eis_passthrough\x18\x03 \x01(\x08\"(\n\x0e\x46lumeDoFnEndDo\x12\x16\n\x0einput_stage_id\x18\x01 \x01(\x03\"2\n\rFlumeDoFnEmit\x12\x10\n\x08stage_id\x18\x01 \x01(\x03\x12\x0f\n\x07item_id\x18\x02 \x01(\x03\"<\n\x0b\x46lumeDepend\x12\x16\n\x0einput_stage_id\x18\x01 \x01(\x03\x12\x15\n\rinput_item_id\x18\x02 \x01(\x03\"%\n\x14\x46lumeCompareFnCreate\x12\r\n\x05label\x18\x01 \x01(\t\"\'\n\x16\x46lumeCompareFnComplete\x12\r\n\x05label\x18\x01 \x01(\t\"~\n\x1a\x46lumeCompareFnStartCompare\x12\x17\n\x0finput1_stage_id\x18\x01 \x01(\x03\x12\x16\n\x0einput1_item_id\x18\x02 \x01(\x03\x12\x17\n\x0finput2_stage_id\x18\x03 \x01(\x03\x12\x16\n\x0einput2_item_id\x18\x04 \x01(\x03\"2\n\x18\x46lumeCompareFnEndCompare\x12\x16\n\x0einput_stage_id\x18\x01 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sight.proto.widgets.pipeline.flume.flume_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLUMEDOFNCREATE._serialized_start=79
  _FLUMEDOFNCREATE._serialized_end=111
  _FLUMEDOFNCOMPLETE._serialized_start=113
  _FLUMEDOFNCOMPLETE._serialized_end=147
  _FLUMEDOFNSTARTDO._serialized_start=149
  _FLUMEDOFNSTARTDO._serialized_end=238
  _FLUMEDOFNENDDO._serialized_start=240
  _FLUMEDOFNENDDO._serialized_end=280
  _FLUMEDOFNEMIT._serialized_start=282
  _FLUMEDOFNEMIT._serialized_end=332
  _FLUMEDEPEND._serialized_start=334
  _FLUMEDEPEND._serialized_end=394
  _FLUMECOMPAREFNCREATE._serialized_start=396
  _FLUMECOMPAREFNCREATE._serialized_end=433
  _FLUMECOMPAREFNCOMPLETE._serialized_start=435
  _FLUMECOMPAREFNCOMPLETE._serialized_end=474
  _FLUMECOMPAREFNSTARTCOMPARE._serialized_start=476
  _FLUMECOMPAREFNSTARTCOMPARE._serialized_end=602
  _FLUMECOMPAREFNENDCOMPARE._serialized_start=604
  _FLUMECOMPAREFNENDCOMPARE._serialized_end=654
# @@protoc_insertion_point(module_scope)
