action_attrs {
  key: "project_id"
  value {
  }
}
action_attrs {
  key: "region"
  value {
  }
}
outcome_attrs {
  key: "time_series"
  value {
    description: "A list of integer values."
    data_type: ST_LIST
  }
}
