# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sight/proto/feature.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19sight/proto/feature.proto\x12\rsight.x.proto\"\x1a\n\tBytesList\x12\r\n\x05value\x18\x01 \x03(\x0c\"\x1e\n\tFloatList\x12\x11\n\x05value\x18\x01 \x03(\x02\x42\x02\x10\x01\"\x1e\n\tInt64List\x12\x11\n\x05value\x18\x01 \x03(\x03\x42\x02\x10\x01\"\xa1\x01\n\x07\x46\x65\x61ture\x12.\n\nbytes_list\x18\x01 \x01(\x0b\x32\x18.sight.x.proto.BytesListH\x00\x12.\n\nfloat_list\x18\x02 \x01(\x0b\x32\x18.sight.x.proto.FloatListH\x00\x12.\n\nint64_list\x18\x03 \x01(\x0b\x32\x18.sight.x.proto.Int64ListH\x00\x42\x06\n\x04kind\"\x89\x01\n\x08\x46\x65\x61tures\x12\x35\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32$.sight.x.proto.Features.FeatureEntry\x1a\x46\n\x0c\x46\x65\x61tureEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.sight.x.proto.Feature:\x02\x38\x01\"6\n\x0b\x46\x65\x61tureList\x12\'\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32\x16.sight.x.proto.Feature\"\xa2\x01\n\x0c\x46\x65\x61tureLists\x12\x42\n\x0c\x66\x65\x61ture_list\x18\x01 \x03(\x0b\x32,.sight.x.proto.FeatureLists.FeatureListEntry\x1aN\n\x10\x46\x65\x61tureListEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.sight.x.proto.FeatureList:\x02\x38\x01\x42\x81\x01\n\x16org.tensorflow.exampleB\rFeatureProtosP\x01ZSgithub.com/tensorflow/tensorflow/tensorflow/go/core/example/example_protos_go_proto\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sight.proto.feature_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026org.tensorflow.exampleB\rFeatureProtosP\001ZSgithub.com/tensorflow/tensorflow/tensorflow/go/core/example/example_protos_go_proto\370\001\001'
  _FLOATLIST.fields_by_name['value']._options = None
  _FLOATLIST.fields_by_name['value']._serialized_options = b'\020\001'
  _INT64LIST.fields_by_name['value']._options = None
  _INT64LIST.fields_by_name['value']._serialized_options = b'\020\001'
  _FEATURES_FEATUREENTRY._options = None
  _FEATURES_FEATUREENTRY._serialized_options = b'8\001'
  _FEATURELISTS_FEATURELISTENTRY._options = None
  _FEATURELISTS_FEATURELISTENTRY._serialized_options = b'8\001'
  _BYTESLIST._serialized_start=44
  _BYTESLIST._serialized_end=70
  _FLOATLIST._serialized_start=72
  _FLOATLIST._serialized_end=102
  _INT64LIST._serialized_start=104
  _INT64LIST._serialized_end=134
  _FEATURE._serialized_start=137
  _FEATURE._serialized_end=298
  _FEATURES._serialized_start=301
  _FEATURES._serialized_end=438
  _FEATURES_FEATUREENTRY._serialized_start=368
  _FEATURES_FEATUREENTRY._serialized_end=438
  _FEATURELIST._serialized_start=440
  _FEATURELIST._serialized_end=494
  _FEATURELISTS._serialized_start=497
  _FEATURELISTS._serialized_end=659
  _FEATURELISTS_FEATURELISTENTRY._serialized_start=581
  _FEATURELISTS_FEATURELISTENTRY._serialized_end=659
# @@protoc_insertion_point(module_scope)
